'use client';

export { default as Dropdown } from '../es/Dropdown';
import { default as Menu } from '../es/Menu';
export { default as Menu } from '../es/Menu';
export const MenuItem = Menu.Item;
export { default as Trigger } from '../es/Trigger';
export { default as Tabs } from '../es/Tabs';
import { default as Tabs } from '../es/Tabs';
export const TabPane = Tabs.TabPane;
export { default as List } from '../es/List';
import { default as List } from '../es/List';
export const ListItem = List.Item;
export const ListItemMeta = List.Item.Meta;
export { default as Typography } from '../es/Typography';
import { default as Typography } from '../es/Typography';
export const TypographyParagraph = Typography.Paragraph;
export const TypographyText = Typography.Text;
export const TypographyTitle = Typography.Title;
export { default as Tag } from '../es/Tag';
import { default as Layout } from '../es/Layout';
export const LayoutSider = Layout.Sider;
export { default as Breadcrumb } from '../es/Breadcrumb';
import { default as Breadcrumb } from '../es/Breadcrumb';
export const BreadcrumbItem = Breadcrumb.Item;
export { default as Statistic } from '../es/Statistic';
export { default as Form } from '../es/Form';
import { default as Form } from '../es/Form';
export const FormItem = Form.Item;
export const useForm = Form.useForm;
export { default as Radio } from '../es/Radio';
import { default as Radio } from '../es/Radio';
export const RadioGroup = Radio.Group;
export { default as Input } from '../es/Input';
